name: Run Tests and Pre-Commit Hooks
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Run tests
        run: coverage run -m pytest -v --durations=5
      - name: Generate coverage badge
        run: coverage-badge -o coverage.svg

  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
